// Descrições em português dos templates oficiais do ComfyUI.
//
// O índice do ComfyUI só traz a descrição em inglês. Aqui está a tradução de
// cada template que roda local, chaveada pelo nome exato do índice. Quando um
// template novo aparecer no ComfyUI antes de ganhar tradução, `descricaoPt`
// monta uma frase genérica a partir das tags e da família — nunca deixa a
// descrição em inglês vazar para a interface em português.
//
// i18n-ignore-start
export const DESCRICOES_PT: Record<string, string> = {
  // ── Use Cases ──────────────────────────────────────────────────────────────
  'templates-1_click_multiple_character_angles-v1.0': 'Envie uma imagem do seu personagem e receba várias vistas dele em ângulos diferentes.',
  'template_ltx2_3_style_transition': 'Aplica a LoRA ltx2.3-transition para criar transições suaves de estilo e de cena. Usa um modelo especializado em mesclar elementos visuais.',
  'template_qwen_image_illustration_lora': 'LoRA de estilo sobre o Qwen-Image. Produz ilustrações que vão de personagens anime fofos a bande dessinée europeia, risografia indie, aquarela de livro infantil, shoujo retrô e graphic novel.',
  'template_sugar_coated_gummy_style_qwen': 'Aplica uma LoRA do Qwen Image que transforma qualquer assunto em um personagem estilo bala de goma azedinha. Digite o nome de um animal no prompt para gerar uma criatura estilizada com cara de comestível.',
  'templates_rob_portrait_light_migration.app': 'Envie a imagem alvo e uma imagem de referência de iluminação. Reilumina a imagem alvo.',
  'templates-portrait_light_migration': 'Envie o retrato do seu personagem e uma imagem de referência de iluminação. Gera uma imagem com a iluminação de referência aplicada e o personagem consistente.',
  'templates-1_click_multiple_scene_angles-v1.0': 'Envie uma imagem da sua cena e gere várias vistas dela em um clique.',
  'templates_mjm_looped_restyler': 'Envie uma imagem inicial e o prompt dela para gerar um vídeo em loop do primeiro ao último quadro.',

  // ── Imagem ─────────────────────────────────────────────────────────────────
  'image_z_image_turbo': 'Modelo base de geração de imagem eficiente, com Diffusion Transformer de fluxo único. Entende inglês e chinês.',
  'image_z_image': 'Base para liberdade criativa. Estética variada com fotorrealismo excepcional; ideal para fine-tuning; responde a prompts negativos; alta diversidade de resultados.',
  'image_qwen_image_edit_2509': 'Edição de imagem avançada com suporte a várias imagens, consistência melhorada e integração com ControlNet.',
  'image_firered_image_edit1_1': 'Envie uma imagem e um prompt de texto para editá-la. Gera uma imagem modificada com consistência de identidade, fusão de vários elementos ou restauração profissional de fotos.',
  'image_flux2_klein_9b_kv_image_edit': 'Envie imagens de referência e um prompt de texto. Gera várias imagens editadas reaproveitando os dados da imagem em cache, para processar mais rápido.',
  'image_ernie_image_turbo': 'Gera imagens a partir de texto com o modelo ERNIE-Image turbo. Descreva a cena e receba uma imagem de alta qualidade, com texto renderizado com precisão e layouts estruturados.',
  'image_ernie_image': 'Gera imagens a partir de texto com o modelo ERNIE-Image. Descreva a cena para produzir visuais detalhados e estruturados, com ampla variedade de estilos.',
  'image_qwen_Image_2512': 'Modelo texto→imagem com realismo humano aprimorado, detalhes naturais mais finos em paisagens e pelagem de animais, e texto renderizado com layout preciso e composição multimodal.',
  'image_qwen_image_edit_2511': 'Troca materiais em objetos (móveis, por exemplo) combinando imagens de referência com o Qwen-Image-Edit-2511.',
  'image_longcat_image_edit': 'Edita imagens com o modelo LongCat-Image-Edit. Aceita instruções em dois idiomas para edições globais, locais, de texto e guiadas por referência, mantendo a consistência visual.',
  'image_flux2': 'Gera imagens fotorrealistas com consistência entre várias referências e renderização profissional de texto.',
  'image_qwen_Image_2512_controlnet': 'Envie uma imagem e escolha o tipo de controle: Canny, HED, profundidade, pose, MLSD, rabisco ou tons de cinza. Gera uma imagem nova guiada pela estrutura escolhida.',
  'image_longcat_text_to_image': 'Gera uma imagem a partir de texto. Descreva a cena em inglês ou chinês e receba uma imagem fotorrealista com texto renderizado com precisão.',
  'image_flux2_klein_image_edit_9b_distilled': 'Modelo destilado da BFL. Qualidade excelente em menos de um segundo. Ótimo para geração em tempo real sem perder qualidade.',
  'image_flux2_klein_image_edit_4b_base': 'Modelo base menor, com relação qualidade/tamanho excepcional. Ideal para rodar local, fazer fine-tuning em hardware limitado e para fluxos eficientes de geração e edição.',
  'image_flux2_klein_image_edit_9b_base': 'Modelo base não destilado da BFL. Máxima flexibilidade e controle. Ótimo para fine-tuning.',
  'image_flux2_text_to_image_9b': 'Modelo destilado da BFL. Qualidade excelente em menos de um segundo. Ótimo para geração em tempo real sem perder qualidade.',
  'image_flux2_text_to_image': 'Texto→imagem com iluminação, materiais e detalhes realistas aprimorados.',
  'image-qwen_image_edit_2511_lora_inflation': 'Envie uma imagem e indique um assunto. Gera uma versão "inflada" dele com a LoRA INFL8 para o Qwen Image Edit.',
  'image_qwen_image_2512_with_2steps_lora': 'Geração com o Qwen-Image 2512 e LoRA Turbo de 2 passos. Digite o prompt para ter um resultado rápido, sacrificando um pouco de qualidade pela velocidade.',
  'image_z_image_turbo_fun_union_controlnet': 'ControlNet multicontrole para o Z-Image-Turbo, com suporte a Canny, HED, profundidade, pose e MLSD.',
  'image_flux2_klein_text_to_image': 'Modelo destilado da BFL. Qualidade excelente em menos de um segundo. Ótimo para geração em tempo real sem perder qualidade.',
  'image_flux2_klein_image_edit_4b_distilled': 'A variante mais rápida da família Klein. Feita para aplicações interativas, prévias em tempo real e usos em produção onde a latência importa.',
  'flux_fill_inpaint_example': 'Preenche partes faltantes de imagens com o Flux.1 Fill (inpainting).',
  'image_qwen_image_edit': 'Edita imagens com edição precisa de texto em dois idiomas e edição dupla de semântica e aparência, usando o modelo MMDiT de 20B do Qwen-Image-Edit.',
  'flux1_dev_uso_reference_image_gen': 'Use imagens de referência para controlar estilo e assunto: mantenha o rosto do seu personagem trocando o estilo artístico, ou aplique estilos artísticos a cenas novas.',
  'Image_capybara_v0_1_text_to_image': 'Digite um prompt para gerar uma imagem. Usa o modelo unificado Capybara para síntese texto→imagem.',
  'Image_capybara_v0_1_image_edit': 'Envie uma imagem ou vídeo e uma instrução em texto. Gera uma saída editada com o modelo Capybara: troca de estilo, substituição de objetos ou mudança da hora do dia.',
  'image_chroma_text_to_image': 'Chroma: modelo Flux aprimorado, com melhor qualidade de imagem e compreensão do prompt para geração texto→imagem impressionante.',
  'flux1_krea_dev': 'Modelo FLUX ajustado para levar o fotorrealismo ao máximo.',
  'flux_dev_checkpoint_example': 'Gera imagens com a versão quantizada fp8 do Flux.1 Dev. Adequado a placas com pouca VRAM: precisa de um único arquivo de modelo, com qualidade um pouco abaixo da versão completa.',
  'image_flux2_fp8': 'Cria mockups de produto aplicando padrões de design em embalagens, canecas e outros itens, com consistência entre várias referências.',
  'sdxl_simple_example': 'Gera imagens de alta qualidade com o SDXL.',
  'flux_fill_outpaint_example': 'Estende imagens além das bordas com o outpainting do Flux.1.',
  'flux_dev_full_text_to_image': 'Gera imagens de alta qualidade com a versão completa do Flux Dev. Exige mais VRAM e vários arquivos de modelo, mas oferece a melhor aderência ao prompt e qualidade de imagem.',
  'flux_kontext_dev_basic': 'Edição inteligente que mantém os personagens consistentes, altera partes específicas sem mexer no resto e preserva o estilo original.',
  'image_qwen_image_instantx_controlnet': 'Gera imagens com o ControlNet InstantX do Qwen-Image, com suporte a Canny, bordas suaves, profundidade e pose.',
  'image_qwen_image': 'Gera imagens com renderização e edição de texto multilíngue excepcionais, usando o modelo MMDiT de 20B do Qwen-Image.',
  'image_kandinsky5_t2i': 'Modelo leve de 2B que gera imagens a partir de prompts em inglês e russo, com alta qualidade visual.',
  'image_chroma1_radiance_text_to_image': 'O Chroma1-Radiance trabalha direto nos pixels em vez de latentes comprimidos, entregando imagens de mais qualidade com menos artefatos e distorções.',
  'image_anima_preview': 'Digite um prompt para gerar uma imagem em estilo anime com o modelo Anima. Ajuste passos e CFG para controlar o resultado. Produz uma ilustração não fotorrealista a partir da sua descrição.',
  'image_qwen_image_edit_2509_relight': 'Reilumina imagens com o Qwen-Image-Edit, com suporte a LoRA.',
  'image_qwen_image_instantx_inpainting_controlnet': 'Inpainting e edição profissional com o ControlNet InstantX do Qwen-Image. Substitui objetos, altera texto, troca o fundo e faz outpainting.',
  'sd3.5_large_canny_controlnet_example': 'Gera imagens guiadas por detecção de bordas com o ControlNet Canny do SD 3.5.',
  'image_chrono_edit_14B': 'Edição de imagem apoiada na compreensão dinâmica dos modelos de vídeo: resultados fisicamente plausíveis, preservando personagem e estilo.',
  'image_flux.1_fill_dev_OneReward': 'Inpainting, outpainting e remoção de objetos, entre outras tarefas, pela equipe bytedance-research.',
  'sd3.5_simple_example': 'Gera imagens com o SD 3.5.',
  'flux_canny_model_example': 'Gera imagens guiadas por detecção de bordas com o Flux.1 Canny.',
  'image_netayume_lumina_t2i': 'Geração anime de alta qualidade, com melhor compreensão de personagens e texturas detalhadas. Ajustado a partir do Neta Lumina com o dataset do Danbooru.',
  'flux_depth_lora_example': 'Gera imagens guiadas por informação de profundidade com uma LoRA do Flux.1.',
  'sdxlturbo_example': 'Gera imagens em um único passo com o SDXL Turbo.',
  'image_qwen_image_union_control_lora': 'Gera imagens com controle estrutural preciso usando a LoRA de ControlNet unificada do Qwen-Image. Suporta Canny, profundidade, lineart, bordas suaves, normal e OpenPose.',
  'image_qwen_image_controlnet_patch': 'Controla a geração com os modelos ControlNet do Qwen-Image. Suporta Canny, profundidade e inpainting por patch do modelo.',
  'image_newbieimage_exp0_1-t2i': 'Gera imagens anime detalhadas com a arquitetura Next-DiT do NewBie Exp0.1. Aceita prompts estruturados em XML para cenas com vários personagens e controle de atributos.',
  'sd3.5_large_depth': 'Gera imagens guiadas por informação de profundidade com o SD 3.5.',
  'flux_redux_model_example': 'Gera imagens transferindo o estilo de imagens de referência com o Flux.1 Redux.',
  'flux_schnell': 'Gera imagens rapidamente com a versão quantizada fp8 do Flux.1 Schnell. Ideal para hardware modesto: só 4 passos por imagem.',
  'flux_schnell_full_text_to_image': 'Gera imagens rapidamente com a versão completa do Flux.1 Schnell. Licença Apache 2.0, só 4 passos por imagem, mantendo boa qualidade.',
  'hidream_i1_full': 'Gera imagens com o HiDream I1 Full: versão completa, com 50 passos de inferência, para a máxima qualidade.',
  'hidream_e1_full': 'Edita imagens com o HiDream E1, modelo profissional de edição por linguagem natural.',
  'hidream_i1_dev': 'Gera imagens com o HiDream I1 Dev: versão equilibrada, com 28 passos, adequada a hardware intermediário.',
  'hidream_i1_fast': 'Gera imagens rapidamente com o HiDream I1 Fast: versão leve, com 16 passos, ideal para prévias rápidas em hardware modesto.',
  'image_omnigen2_image_edit': 'Edita imagens com instruções em linguagem natural usando o OmniGen2, com suporte a renderização de texto.',
  'sdxl_revision_text_prompts': 'Gera imagens transferindo conceitos de imagens de referência com o SDXL Revision.',
  'image_ovis_text_to_image': 'O Ovis-Image é um modelo texto→imagem de 7B otimizado para renderizar texto com alta qualidade dentro das imagens. Roda bem com recursos limitados e acerta imagens com conteúdo textual.',
  'sdxl_refiner_prompt_example': 'Melhora imagens do SDXL usando modelos refinadores.',
  'image_omnigen2_t2i': 'Gera imagens de alta qualidade a partir de texto com o modelo multimodal unificado de 7B do OmniGen2, de arquitetura de duas vias.',
  'sd3.5_large_blur': 'Gera imagens guiadas por imagens de referência desfocadas com o SD 3.5.',

  // ── Vídeo ──────────────────────────────────────────────────────────────────
  'video_wan2_2_14B_i2v': 'Transforma imagens estáticas em vídeo, com controle preciso de movimento e preservação de estilo, usando o Wan 2.2.',
  'video_wan2_2_14B_t2v': 'Gera vídeos de alta qualidade a partir de texto, com controle estético cinematográfico e movimento dinâmico, usando o Wan 2.2.',
  'video_ltx2_3_i2v': 'Envie uma imagem para gerar um vídeo com movimento mais consistente e detalhes finos, incluindo melhor suporte a formato retrato e qualidade de áudio.',
  'video_ltx2_3_ia2v': 'Envie uma imagem e um arquivo de áudio para gerar um vídeo de alta qualidade com movimento labial sincronizado, usando o LTX-2.3.',
  'video_ltx2_3_flf2v': 'Envie uma imagem inicial para gerar uma sequência de vídeo. Cria um vídeo curto com estilo e movimento consistentes, começando pelo quadro fornecido.',
  'video_ltx2_3_t2v': 'Gera um vídeo a partir de texto, opcionalmente com uma imagem de referência. Vídeo de alta qualidade com movimento, áudio e detalhes melhorados, em retrato ou paisagem.',
  'video_ltx2_3_id_lora': 'Gera vídeos personalizados com áudio sincronizado a partir de texto, imagem de referência e um clipe curto de áudio. A ID-LoRA adapta a aparência e a voz de uma pessoa em um único modelo.',
  'video_ltx2_i2v': 'Transforma imagens estáticas em vídeo com geração sincronizada de áudio e vídeo, usando o LTX-2. Sincronia labial expressiva, movimento natural e bom desempenho.',
  'video_ltx2_t2v': 'Gera vídeos de alta qualidade a partir de texto com áudio e vídeo sincronizados, usando o LTX-2. Sincronia labial expressiva, movimento dinâmico e bom desempenho.',
  'video_wan_vace_14B_v2v': 'Gera vídeos controlando vídeos de entrada e imagens de referência com o Wan VACE.',
  'video_ltx2_i2v_lora': 'Envie qualquer imagem para aplicar o efeito da LoRA Squish It. Gera uma animação de "amassar" com o modelo LTX-2 I2V.',
  'video_wan2_2_14B_flf2v': 'Gera transições de vídeo suaves definindo o quadro inicial e o final.',
  'video_wan2_2_14B_fun_control': 'Gera vídeos guiados por pose, profundidade e bordas com o Wan 2.2 Fun Control.',
  'video_ltx2_i2v_distilled': 'Transforma imagens estáticas em vídeo com áudio sincronizado, usando o modelo destilado do LTX-2. Otimizado para gerar mais rápido mantendo a qualidade.',
  'video_ltx2_t2v_distilled': 'Gera vídeos de alta qualidade a partir de texto com áudio sincronizado, usando o modelo destilado do LTX-2. Otimizado para gerar mais rápido mantendo a qualidade.',
  'video_ltx2_canny_to_video': 'Gera vídeos de alta qualidade a partir de detecção de bordas (Canny), com áudio e vídeo sincronizados, usando o LTX-2. Controle preciso das bordas e consistência estrutural.',
  'video_ltx2_depth_to_video': 'Gera vídeos de alta qualidade a partir de mapas de profundidade, com áudio e vídeo sincronizados, usando o LTX-2. Controle preciso de profundidade e noção espacial.',
  'video_hunyuan_video_1.5_720p_i2v': 'Anima imagens paradas em vídeo com controle preciso de movimento e câmera. Mantém a consistência visual e dá vida a fotos e ilustrações com movimentos suaves e naturais.',
  'video_wan2_2_5B_ti2v': 'Geração rápida de vídeo a partir de texto ou imagem com 5B de parâmetros. Otimizado para protótipos rápidos e exploração criativa.',
  'video_wan2_2_14B_s2v': 'Transforma imagem estática e áudio em vídeo, com sincronia perfeita e geração de até um minuto.',
  'video_wan_vace_inpainting': 'Edita regiões específicas de vídeos preservando o entorno. Ótimo para remover ou substituir objetos.',
  'video_wan2_2_14B_fun_inpaint': 'Gera vídeos a partir do quadro inicial e do final com o Wan 2.2 Fun Inp.',
  'ltxv_image_to_video': 'Gera vídeos a partir de imagens paradas.',
  'video_hunyuan_video_1.5_720p_t2v': 'Gera vídeos 720p de alta qualidade a partir de texto, com controle cinematográfico de câmera, expressões emocionais e simulação de física. Estilos realista, anime e 3D, com renderização de texto.',
  'wan2.1_fun_control': 'Gera vídeos guiados por pose, profundidade e bordas com o ControlNet do Wan 2.1.',
  'video_wan_vace_14B_ref2v': 'Cria vídeos que seguem o estilo e o conteúdo de uma imagem de referência. Perfeito para vídeo com estilo consistente.',
  'video_wan2_1_infinitetalk': 'Envie uma imagem de origem e o áudio alvo. Gera um vídeo dublado de corpo inteiro com movimento sincronizado, preservando identidade, fundo e movimento de câmera.',
  'video_wanmove_480p': 'Gera vídeos a partir de uma única imagem com o Wan-Move, com controle fino de movimento ponto a ponto guiado por trajetórias.',
  'video_wan_vace_outpainting': 'Gera vídeos estendidos ampliando o quadro com o outpainting do Wan VACE.',
  'video_wan2_2_5B_fun_control': 'Controle de vídeo por várias condições: pose, profundidade e bordas. Tamanho compacto de 5B para experimentação.',
  'video_humo': 'Gera vídeos a partir de áudio, imagem e texto, mantendo a sincronia labial do personagem.',
  'text_to_video_wan': 'Gera vídeos a partir de texto com o Wan 2.1.',
  'video_wan2_2_14B_fun_camera': 'Gera vídeos com controle de câmera (pan, zoom e rotação) usando o Wan 2.2 Fun Camera Control.',
  'image_to_video_wan': 'Gera vídeos a partir de imagens com o Wan 2.1.',
  'wan2.1_flf2v_720_f16': 'Gera vídeos controlando o primeiro e o último quadro com o Wan 2.1 FLF2V.',
  'video_kandinsky5_i2v': 'Modelo leve de 2B que gera vídeos a partir de prompts em inglês e russo, com alta qualidade visual.',
  'video_wan_vace_flf2v': 'Gera transições de vídeo suaves definindo o quadro inicial e o final. Aceita sequências de keyframes personalizadas.',
  'video_kandinsky5_t2v': 'Modelo leve de 2B que gera vídeos a partir de prompts em inglês e russo, com alta qualidade visual.',
  'video_capybara_v0_1_video_edit': 'Envie uma imagem ou vídeo e uma instrução em texto para gerar ou editar. Produz uma imagem ou vídeo novo ou editado conforme a instrução.',
  'video_capybara_v0_1_image_to_video': 'Envie uma imagem e uma instrução em texto. Gera um vídeo em que a entrada é editada conforme a instrução, preservando estrutura e coerência temporal.',
  'video_wan2.1_alpha_t2v_14B': 'Gera vídeo a partir de texto com canal alfa: fundos transparentes e objetos semitransparentes.',
  'txt_to_image_to_video': 'Gera vídeos criando primeiro imagens a partir de texto.',
  'video_wan_ati': 'Geração de vídeo controlada por trajetória.',
  'video_wan2_2_5B_fun_inpaint': 'Inpainting de vídeo eficiente a partir do quadro inicial e do final. O modelo de 5B permite iterações rápidas para testar fluxos.',
  'ltxv_text_to_video': 'Gera vídeos a partir de texto.',
  'video_wan2.1_fun_camera_v1.1_14B': 'Gera vídeos de alta qualidade com controle avançado de câmera usando o modelo completo de 14B.',
  'video_wan_vace_14B_t2v': 'Transforma descrições em texto em vídeos de alta qualidade. Suporta 480p e 720p com o modelo VACE-14B.',
  'video_wan2.1_fun_camera_v1.1_1.3B': 'Gera vídeos dinâmicos com movimentos de câmera cinematográficos usando o modelo Wan 2.1 Fun Camera 1.3B.',
  'wan2.1_fun_inp': 'Gera vídeos a partir do quadro inicial e do final com o inpainting do Wan 2.1.',
  'hunyuan_video_text_to_video': 'Gera vídeos a partir de texto com o modelo Hunyuan.',

  // ── Utilitários ────────────────────────────────────────────────────────────
  'utility_sdpose_ood_video_to_pose_map': 'Envie um vídeo para extrair os pontos de pose e gerar um mapa de pose. Detecta várias pessoas e usa um SDPose aprimorado para extrair o corpo inteiro com precisão.',
  'utility_sdpose_multi_person_video': 'Envie um vídeo para detectar poses humanas. Funciona com uma pessoa ou várias na mesma cena.',
  'utility_sdpose_multi_person': 'Envie uma imagem para detectar poses humanas. Funciona com uma pessoa ou várias na mesma cena.',
  'utility_sdpose_ood_image_to_pose': 'Envie uma imagem para extrair os pontos de pose e gerar o mapa de pose correspondente com o modelo SDPose-OOD.',
  'utility_z_image_turbo_2k_upscaler.app': 'Envie uma imagem para ampliá-la até 2K com o modelo Z-Image-Turbo.',
  'image_qwen_image_layered': 'Decompõe uma imagem em camadas RGBA editáveis para recolorir, substituir, redimensionar e reposicionar com alta fidelidade, usando o Qwen-Image-Layered.',
  'image_lotus_depth_v1_1': 'Estimativa de profundidade monocular com o Lotus Depth: eficiente, sem treino específico e com alta retenção de detalhes.',

  // ── Primeiros passos ───────────────────────────────────────────────────────
  'gsc_creator_2_3': 'Aprenda a ampliar uma imagem e gerar um prompt automaticamente com o Z Image Turbo.',
  'gsl_starter_1_1': 'Aprenda a gerar uma imagem, baixar modelos, conectar nós, rodar um workflow e salvar a imagem com o Z-Image Turbo.',
  'gsl_starter_1_2': 'Aprenda a carregar imagens, gerar um vídeo e encontrar um nó usando o Wan 2.2.',
  'gsl_starter_1_3': 'Aprenda a reiluminar um produto, entrar em um subgrafo e reativar um nó com o Qwen Image Edit.',
  '01_get_started_text_to_image': 'Gera imagens a partir de texto com o modelo Z-Image-Turbo.',
  '02_qwen_Image_edit_subgraphed': 'Edite suas imagens com o Qwen-Image-Edit, o modelo aberto mais recente.',
  '03_video_wan2_2_14B_i2v_subgraphed': 'Gera vídeos a partir de uma imagem com o Wan2.2 14B.',
  'default': 'Gera imagens a partir de texto.',
  'hidream_e1_1': 'Edita imagens com o HiDream E1.1: qualidade e precisão de edição superiores ao HiDream-E1-Full.',
  // ── Só no catálogo do Comfy Cloud (não vêm no pacote do ComfyUI 0.19) ───────
  'image_z_image_turbo_int8': 'Gera imagens fotorrealistas com o Z-Image-Turbo em int8, variante destilada de 6B otimizada para inferência em menos de um segundo com 8 passos. Recebe um prompt e devolve uma imagem. Ideal para iteração criativa rápida, arte conceitual realista e protótipos visuais.',
  'image_krea2_turbo_t2i': 'Gera imagens a partir de texto com o Krea 2, modelo base voltado a qualidade estética e controle criativo, com foco em estilos expressivos e artísticos. Ideal para explorar arte conceitual, brainstorm visual e imagens estilizadas para design.',
  'image_krea2_turbo_int8_image_style_reference': 'Gera imagens com o Krea-2 Turbo tomando como referência o estilo de 1 ou 2 imagens enviadas, no formato Int8 Convrot (mais rápido e com mais qualidade). Aceita até duas referências e produz uma saída estilizada, com LoRA opcional. Ideal para casar um estilo artístico, manter visual de marca e testar transferência de estilo rapidamente.',
  'image_krea2_turbo_t2i_int8': 'Gera imagens com o Krea-2 Turbo destilado em Int8 Convrot, formato com mais qualidade que fp8 e geralmente mais rápido na maioria das placas. Sem arquivos de entrada, produz uma imagem, com LoRA de estilo opcional. Ideal para iterar arte conceitual, gerar lotes de assets para jogos e marketing e explorar o equilíbrio entre velocidade e qualidade.',
  'image_qwen_image_edit_2511_int8': 'Edita imagens com o Qwen Image Edit 2511 em Int8: modelo quantizado, mais rápido, mantendo a qualidade. Uma imagem de entrada, uma editada de saída. Ideal para edição de retratos com consistência do personagem, fusão de fotos de grupo e ajustes de design industrial.',
  'video_bernini_r_image_editing': 'Gera uma imagem editada com iluminação coerente e mostra a comparação antes/depois lado a lado. Ideal para reiluminar retratos e produtos, manter a mesma luz num conjunto de fotos e fotografia de catálogo para e-commerce.',
  'image_anima_base_v1': 'Descreva uma ilustração anime ou artística no prompt. Gera uma imagem não fotorrealista focada em conceitos, personagens ou estilos de anime.',
  'image_anima_lllite_any_control_to_image': 'Aplica controle condicional leve, no estilo LoRA, a imagens anime do Anima-Base v1.0 com o ControlNet-LLLite: uma entrada de condição e uma máscara opcional para inpainting, uma imagem de saída. Ideal para inpainting anime com máscara dinâmica, transferência de estilo a partir de lineart ou esboço e geração controlada de personagens.',
  'image_anima_lllite_image_inpainting': 'Faz inpainting em imagens anime com o Anima LLLite, variante leve de ControlNet com correções de baixo rank para edição precisa por máscara. Uma imagem de entrada, uma saída com inpainting e uma vista de comparação. Ideal para corrigir detalhes de personagens, remover objetos e restaurar fundos.',
  'image_anima_lllite_depth_control_to_image': 'Gera ilustrações anime a partir de um mapa de profundidade com o Anima LLLite, que aplica uma correção leve de ControlNet para controle espacial preciso. Uma imagem de entrada, duas saídas e uma comparação. Ideal para reconstrução de cena, passes de profundidade em VFX e preparo de assets de RA.',
  'image_boogu_image_0_1_edit_int8': 'Edita imagens com o Boogu Image Edit, agora em quantização convrot int8: mais rápido e com mais qualidade que fp8. Uma imagem de entrada, uma editada de saída. Ideal para edições rápidas, processamento em lote e para quem quer as vantagens do formato int8.',
  'image_boogu_image_0_1_edit': 'Edita imagens com o modelo por instrução do Boogu: uma imagem de entrada, uma editada de saída e uma comparação lado a lado.',
  'image_z_image_int8': 'Gera imagens diversas e de alta qualidade a partir de texto com o Z-Image em Int8, que usa um transformer não destilado para aderência precisa ao prompt e ampla cobertura de estilos. Sem arquivos de entrada, uma imagem de saída. Ideal para projetos profissionais, treino de LoRA e situações que pedem prompt negativo forte e alta diversidade de composição.',
  'image_joyai_image_edit': 'Edita imagens seguindo instruções em linguagem natural com o JoyAI-Image-Edit, que usa compreensão multimodal para modificações precisas e com noção espacial. Uma imagem de referência, uma editada de saída e uma comparação. Ideal para retoques guiados por instrução, substituição de objetos em regiões específicas e ajustes complexos de cena.',
  'image_hidream_o1_dev': 'Digite um prompt e, opcionalmente, envie imagens de referência. Gera uma imagem de alta resolução (até 2048×2048) com suporte a texto→imagem, edição e personalização por sujeito.',
  'image_hidream_o1': 'Digite um prompt e, opcionalmente, envie imagens de referência. Gera uma imagem de alta resolução até 2048×2048 com texto→imagem, edição ou personalização por sujeito.',
  'image_boogu_image_0_1_turbo_t2i': 'Gera imagens de alta qualidade a partir de texto com o Boogu Turbo, pipeline destilado de 10B que produz fotorrealismo em só 4 passos. Um prompt de entrada, uma imagem 1024×1024 de saída. Ideal para protótipos fotorrealistas, visuais de marketing e imagens com texto em dois idiomas.',
  'image_lens_t2i': 'Digite um prompt e escolha resolução e proporção. Gera uma imagem de alta qualidade com o eficiente modelo Lens.',
  'image_lens_turbo_t2i': 'Digite um prompt e escolha resolução, proporção e número de passos. Gera uma imagem de alta qualidade com o modelo Lens.',
  'image_mage_flow_turbo_t2i_int8': 'Gera imagens de alta qualidade a partir de texto com o compacto Mage-Flow Turbo (4B), sem arquivos de entrada e uma imagem de saída. Suporta resolução nativa de 512 a 2048 pixels por lado em qualquer proporção, inclusive 4:1. Ideal para visualização rápida de conceitos, geração de assets e protótipos de baixa latência em hardware modesto.',
  'image_mage_flow_t2i_int8': 'Gera imagens de alta resolução a partir de texto com o Mage-Flow, modelo de difusão compacto de 4B que produz uma imagem em resolução nativa de 512 a 2048 pixels por lado. Ideal para visualização rápida de conceitos, geração de assets e pesquisa com pouca computação.',
  'image_mage_flow_edit_turbo_int8': 'Edita imagens com uma foto de referência e instruções em texto usando o Mage-Flow-Edit Turbo, modelo destilado de 4B que entrega o resultado em 4 passos. Recebe de 1 a 3 referências e um prompt e devolve a imagem editada. Ideal para transferência de estilo rápida, troca de fundo e edição interativa.',
  'image_mage_flow_edit_int8': 'Edita imagens seguindo instruções em linguagem natural com o Mage-Flow-Edit: troca de fundo, mudança de estilo, edições localizadas e restauração, com até três imagens de referência. Uma imagem de entrada, uma editada de saída e uma comparação. Ideal para retoque criativo, styling de produto e restauração de fotos antigas.',
  'image_pixeldit_t2i': 'Digite um prompt e, opcionalmente, um prompt negativo. Gera uma imagem de 1024 px com o PixelDiT, transformer de difusão em pixels, sem VAE.',
  'image_sdxl_simple': 'Gera imagens de alta qualidade a partir de texto com o SDXL 1.0 num fluxo direto de texto→imagem. Ideal para visualizar conceitos rapidamente, brainstorm criativo e protótipos visuais.',
  'template_qwen_image_edit_2511_systms_action': 'Envie a imagem alvo e use a frase de ativação "action the [coisa]" (por exemplo, "action the scene"). Gera uma versão do seu assunto como boneco articulado, com juntas, material plástico e detalhes pintados.',
  'templates_rob_image_to_real.app': 'Envie uma ilustração e gere uma versão realista com o Qwen Image Edit 2509 e a LoRA Anything2Real.',
  'template_qwen_Image_2512_360_lora': 'Gera imagens 360° em projeção equirretangular a partir de texto, com uma LoRA de rank 128 sobre o modelo MMDiT de 20B.',
  'utility_seedvr2_image_upscale': 'Envie uma imagem para ampliá-la com o SeedVR2 e gerar uma saída em alta definição.',
  'utility_seedvr2_7b_int8_upscale_image': 'Amplia imagens com o SeedVR2 7B Int8, modelo de difusão de um passo que aumenta a resolução com treino adversarial e atenção por janela adaptativa. Uma imagem de entrada, uma ampliada de saída, com mais detalhe e nitidez. Ideal para restaurar fotos de baixa resolução, preparar material para impressão e recuperar imagens levemente degradadas.',
  'utility_seedvr2_3b_int8_upscale_image': 'Amplia imagens com o SeedVR2 3B Int8, modelo de restauração por difusão de um passo, com alta qualidade e consistência temporal melhorada. Ideal para restaurar material degradado, ampliar baixa resolução e melhorar mídia de arquivo.',
  'utility_pid_latent_upscale_dit': 'Receba um latente de um modelo de difusão e escolha um checkpoint PiD. Gera a imagem decodificada em alta resolução, com ampliação de 4× ou 8× num único passo.',
  'utility_image_upscale_supir': 'Restaura e melhora imagens com o prior generativo do SUPIR e orientação por texto. Aceita uma imagem e um prompt opcional para restauração inteligente de alta qualidade.',
  'utility_image_segment_sam3': 'Usa o SAM3 para segmentar o assunto principal ou um conteúdo específico de uma foto, isolando objetos ou regiões. Uma imagem de entrada, uma máscara segmentada de saída.',
  'templates_doc_workbox_klein_9b_image_extend': 'Usa o FLUX.2 Klein 9B para estender e expandir o conteúdo da imagem de forma inteligente. Envie uma imagem para gerar um outpainting contínuo e composições ampliadas.',
  'utility_depth_anything3_image_depth_estimation': 'Envie uma imagem. Gera um mapa de profundidade com o Depth Anything 3 e mostra a comparação com o original lado a lado. Ideal para reconstrução 3D de cena, preparo de assets de RA/RV e passes de profundidade em efeitos visuais.',
  'image_marigold_v2_depth_estimation': 'Estima a profundidade da cena a partir de uma imagem com o Marigold V2, gerando um mapa em que as áreas mais claras estão mais perto e as mais escuras, mais longe.',
  'image_marigold_v2_albedo_estimation': 'Estima o albedo de uma imagem com o Marigold V2. Separa a cor das superfícies da iluminação e do sombreado, produzindo um mapa de albedo útil para reiluminar, analisar materiais e criar assets 3D.',
  'utility_moge_depth_estimation': 'Envie uma imagem RGB e ajuste a resolução de inferência e o tamanho do lote. Gera uma prévia colorida de profundidade e o mapa de profundidade bruto.',
  'image_marigold_v2_surface_normal_estimation': 'Estima as normais de superfície de uma imagem com o Marigold V2. Gera um mapa de normais com a orientação das superfícies da cena, útil para reconstrução 3D, reiluminação e processamento que leva a geometria em conta.',
  'utility_birefnet_remove_background': 'Envie uma imagem com qualquer fundo. Gera uma versão sem o fundo e uma máscara de segmentação precisa.',
  'templates_hellorob_facegen_skindetail_upscale': 'Workflow de um clique que gera o retrato de um personagem, refina e acrescenta detalhes de pele e amplia para 4K. Tudo em menos de 60 segundos.',
  'templates-qwen_multiangle.app': 'Gera variações de ângulo de câmera da sua imagem com um nó de câmera 3D fácil de usar.',
  'video_ltx2_5_i2v': 'Gera vídeo a partir de uma única imagem com o LTX-2.5, produzindo um clipe de alta fidelidade, qualidade de pixel de ponta e multishot nativo, que mantém personagem, ambiente e iluminação entre cenas conectadas. Ideal para produção cinematográfica, criação de planos de VFX e pipelines que precisam de geração de vídeo rápida e local.',
  'video_ltx2_5_t2v': 'Gera vídeo cinematográfico a partir de texto com o LTX-2.5, modelo de difusão pronto para produção que entrega um único arquivo de vídeo, com upscale espacial opcional. Ideal para pré-visualização de filmes, storyboards de comerciais e pipelines de conteúdo em volume.',
  'video_ltx2_5_flf2v': 'Gera um vídeo a partir de imagens de referência do primeiro e do último quadro com o LTX-2.5, fundindo as duas numa única sequência animada. Ideal para planos de transição, morphing entre dois assuntos ou cenas e narrativas em vários planos a partir de imagens paradas.',
  'video_wan_animate2': 'Anima um personagem parado com um vídeo-guia usando o Wan Animate 2, transferindo o movimento direto dos quadros, sem extração de pose nem esqueleto. Preserva a identidade do personagem de referência e gera fundo e movimento de câmera novos a partir do prompt. Ideal para transferência de movimento, imitação de ações e substituição de animação de personagem.',
  'video_wan_animate2_distilled': 'Anima um personagem parado com um vídeo-guia usando o Wan Animate 2, transferindo o movimento direto dos quadros, sem extração de pose. Preserva a identidade do personagem e gera fundo e câmera novos a partir do prompt. Esta versão destilada é mais eficiente, mantendo alta fidelidade e forte preservação de identidade.',
  'video_wan21_scail2_character_replacement': 'Envie 1 imagem de referência do personagem e 1 vídeo-guia. Gera um vídeo animado do personagem seguindo o movimento do vídeo-guia. Ideal para animação de personagens, substituição dentro de vídeos e transferência de movimento.',
  'video_wan21_scail2_character_replacement_int8': 'Anima um personagem de referência com um vídeo-guia ou substitui personagens por completo com o SCAIL-2 Int8, com mais qualidade que fp8 e mais rápido. Uma imagem de referência e um vídeo-guia de entrada, uma sequência animada com a identidade trocada de saída. Ideal para trocas de identidade, animação guiada por animais e cenas com vários personagens sem passar por pose intermediária.',
  'video_ltx2_3_ic_lora': 'Gera vídeos com o LTX 2.3 e IC-LoRA usando entradas de controle alinhadas, como profundidade, pose ou bordas.',
  'video_bernini_r_video_editing': 'Gera um vídeo editado com reiluminação consistente usando o Bernini-R. Ideal para reiluminar retratos e produtos, fotografia de catálogo para e-commerce e manter a mesma luz num conjunto de fotos.',
  'video_ltx_2_audio_to_video': 'Envie um arquivo de áudio e um quadro inicial. Gera um vídeo sincronizado com o áudio usando o modelo LTX-2.',
  'video_causal_forcing_i2v': 'Digite um prompt e escolha o checkpoint. Gera um vídeo de alta qualidade com o Causal Forcing ou Causal Forcing++ em 1 a 4 passos de inferência.',
  'video_wan2_2_14B_animate': 'Framework unificado de animação e substituição de personagens, com reprodução precisa de movimento e expressão.',
  'video_ltx2_pose_to_video': 'Gera vídeos de alta qualidade a partir de orientação por pose, com áudio e vídeo sincronizados, usando o LTX-2. Controle preciso de pose, movimento expressivo e bom desempenho.',
  'video-wan21_scail': 'Controle de pose SCAIL em um toque, baseado na composição da imagem de referência.',
  'video_wanmove_480p_hallucination': 'Usa o WanMove para gerar imagens dinâmicas a partir de trajetórias e criar efeitos de vídeo com ilusão de devaneio.',
  'video_wan_dancer': 'Gera vídeos de dança coerentes com duração de minutos a partir de música, com o framework hierárquico Wan Dancer. Recebe um arquivo de música e uma imagem de referência e produz vídeos de dança em alta resolução, com estrutura global e continuidade temporal.',
  'template_ltx2_3_lora_googly_eyes': 'LoRA do LTX 2.3 que coloca olhos esbugalhados em qualquer pessoa do vídeo de entrada. Usa a LoRA Googlyeyes de TheBurgstall.',
  'templates_rob_wan_ati_motion_control': 'Envie uma imagem e use o nó Animate Path para desenhar trajetórias e criar um efeito de vídeo viral.',
  'template_animate_diff_loops': 'Envie uma imagem e receba uma animação em loop contínuo.',
  'templates_ingi_infl8': 'Envie a imagem de um personagem e digite o prompt. Gera um vídeo animado em que o personagem se expande com efeito de inflar.',
  'templates_purz_animatediff_simple_weighted_ipadapters_looping_animation': 'Arraste um conjunto de imagens e deixe o AnimateDiff "sonhar" através delas, gerando uma animação em loop com IPAdapters ponderados.',
  'templates_shane_video_restyle': 'Usa um vídeo base e uma imagem de referência estilizada para criar o vídeo estilizado com o WAN 2.1 VACE.',
  'templates_mjm_airt_machIne': 'Envie qualquer imagem para gerar um vídeo de IA único em loop. O workflow usa um LLM para criar cinco prompts, produz imagens e clipes e os costura num loop final contínuo.',
  'templates_mjm_Injected': 'Envie uma imagem inicial e um vídeo de máscara definindo a área de injeção. Gera um vídeo dinâmico injetando padrões de ruído de um vídeo dedicado, com prompts gerados automaticamente por IA.',
  'template-Animation_Trajectory_Control_Wan_ATI': 'Desenhe a trajetória de movimento que você quer para a imagem de entrada.',
  'utility_seedvr2_3b_int8_upscale_video': 'Amplia e restaura vídeos com o SeedVR2 3B Int8, modelo de difusão de um passo que aumenta a resolução mantendo a consistência temporal entre quadros. Um vídeo degradado de entrada, um vídeo restaurado em alta resolução de saída. Ideal para restaurar material antigo, ampliar vídeos de baixa resolução e melhorar mídia de arquivo.',
  'utility_video_upscale': 'Envie um vídeo e amplie-o para uma resolução maior com o Wan 2.2.',
  'utility_depth_anything3_video_depth_estimation': 'Envie uma imagem para gerar um mapa de profundidade voltado a vídeo. Produz uma imagem de profundidade pronta para workflows seguintes. Ideal para geração de vídeo com controle de profundidade, pré-processamento de cena 3D e mapeamento de profundidade para animação.',
  'utility-depthAnything-v2-relative-video': 'Converte um vídeo em um mapa de profundidade temporalmente estável.',
  'utility-lineart-video': 'Converte um vídeo em lineart/Canny para usar em processadores de controle.',
  'utility_video_segment_sam3': 'Usa o SAM3 para segmentar o assunto principal ou um conteúdo específico de um vídeo, isolando objetos ou regiões. Um vídeo de entrada, máscaras segmentadas de saída.',
  'utility_video_frame_interpolation': 'Envie um vídeo e escolha o modelo de interpolação de quadros, RIFE ou FILM, para gerar um vídeo mais suave e com mais quadros por segundo.',
  'utility-frame_interpolation-film': 'Suaviza vídeos com baixa taxa de quadros.',
  'utility_gimm_frame_interpolation': 'Gera quadros intermediários entre os quadros existentes para um movimento mais suave. Um vídeo de entrada, uma saída fluida com mais quadros por segundo e a mesma duração.',
  'utility_void_video_inpainting': 'Envie um vídeo e marque com máscara o objeto que quer remover. Gera um vídeo limpo, sem o objeto e sem suas interações físicas.',
  'utility-openpose-video': 'Converte um vídeo em um mapa de controle de pose temporalmente estável.',
  'template_ltx2_3_obscura_remova_lora_remove_object_from_video': 'Envie um vídeo e descreva no prompt o objeto a remover do primeiro plano.',
  'template_ltx2_3_lora_video_outpainting': 'Outpainting de vídeo com a IC LoRA de Video Outpainting do LTX 2.3. Expanda seu vídeo em qualquer direção.',
  'template_ltx2_3_lora_remove_subtitles_from_video': 'Envie um vídeo com legendas ou textos sobrepostos e remova os elementos de texto com um clique.',
  'template_ltx2_3_remove_watermark_from_video': 'Envie um vídeo com marcas d\'água e remova-as com um clique.',
  'template_ltx2_3_lora_restore_archival_footage': 'Envie um vídeo ou material de arquivo e restaure-o com 1 clique.',
  'templates_shane_change_any_objects': 'Use um prompt simples para mascarar objetos de um vídeo e substituí-los por prompt ou por uma imagem de referência opcional. Modelos: SAM3 + WAN 2.1 VACE (inpainting).',
  'template_ltx2_3_ic_lora_ingredients': 'Gera clipes curtos visualmente consistentes com uma folha de referência que inventaria personagens, objetos e locais. Recebe uma imagem de referência composta e um prompt dividido descrevendo a ação, e devolve um clipe. Ideal para animação centrada em personagens, visualização consistente de objetos e cenas em locais específicos.',
  'template_purz_wan22_animate_auto_character_replace': 'Envie um vídeo e a imagem de um personagem. Substitui automaticamente o personagem do vídeo com o modelo Wan2.2 Animate.',
  'templates-wan2_1_infinitetalk_music': 'Envie a imagem de um personagem e um arquivo de áudio. Gera um vídeo com sincronia labial, em que a boca do personagem acompanha o áudio.',
  'template_rob_split_stack_qwen_multi_wan22': 'Envie 1 imagem e gere 5 ângulos alternativos para usar como quadros iniciais no Wan2.2. Cada vídeo é empilhado horizontalmente num vídeo final 9×16.',
  'templates_liveportrait.app': 'Envie um retrato e um vídeo de expressão de referência. Gera um vídeo do retrato com as expressões faciais da referência.',
  // ── Abertos que o índice novo declara (`openSource: true`): MiniMax H3, Ideogram 4 e workflows só de nós ──
  'image_ideogram4_t2i': 'Digite um prompt ou uma descrição estruturada em JSON. Gera uma imagem com controle preciso de layout, cor e estilo usando o Ideogram 4.0.',
  'image_ideogram4_t2i_int8': 'Gera imagens a partir de texto com o Ideogram v4, modelo de pesos abertos de ponta, com renderização de texto e controle de layout excepcionais. Sem arquivos de entrada, uma imagem de saída. Ideal para visuais de marketing, mockups de design com tipografia precisa e arte em alta resolução com composição controlada.',
  'video_fastvideo_fasth3_i2v': 'Gera vídeo com áudio nativo sincronizado a partir de uma única imagem, usando o MiniMax H3 com o checkpoint FastH3 de 8 passos. Uma imagem produz um vídeo com voz, efeitos sonoros e música numa só passada. Ideal para animar retratos, dar vida a fotos de produto e clipes rápidos para redes sociais.',
  'video_minimax_h3_i2v': 'Transforma uma imagem inicial num clipe curto de alta qualidade com o MiniMax H3, modelo multimodal unificado que gera imagem e áudio sincronizado numa só passada. Uma imagem de entrada, um vídeo de saída, com texto ou mídia de referência opcionais para guiar movimento, estilo ou som. Ideal para visualizar conceitos, testar animação de personagens e criar clipes para redes sociais já com desenho de som.',
  'video_minimax_h3_r2v': 'Gera um vídeo novo alimentando o MiniMax H3 com uma imagem de referência, até nove imagens, três vídeos e três clipes de áudio junto com um prompt. O modelo copia identidade do personagem, movimento, câmera, voz ou estilo dessas fontes e produz áudio estéreo nativo numa só passada. Saída: um MP4 de até 2K a 24 fps, com cerca de 15 segundos. Ideal para animação com personagem consistente, transferência de estilo em vídeo e conteúdo com áudio sincronizado.',
  'video_minimax_h3_t2v': 'Gera vídeo com áudio estéreo nativo direto do texto com o MiniMax H3, modelo omni-modal que sintetiza voz, efeitos sonoros e música numa só passada. Saída de até 2K a 24 fps, com cerca de 15 segundos, sem arquivos de entrada. Ideal para visualizar conceitos, conteúdo para redes sociais e narrativas com áudio sincronizado.',
  'video_fastvideo_fasth3_t2v': 'Gera vídeo e áudio sincronizados direto do texto com um modelo destilado de oito passos, produzindo um vídeo sem arquivos de entrada. Ideal para protótipos rápidos de texto→vídeo, conteúdo audiovisual e narrativas em que velocidade importa mais que o máximo de detalhe.',
  'video_minimax_h3_multiframe_reference': 'Gera vídeo a partir de várias imagens paradas com o MiniMax H3, ancorando até quatro quadros de referência em qualquer ponto da linha do tempo para controlar movimento e composição. Ideal para continuar clipes existentes, forçar momentos narrativos em pontos específicos e produzir material com áudio nativo sincronizado.',
  'video_minimax_h3_fun_controlnet_union': 'Gera vídeos a partir de um vídeo de referência de pose com o MiniMax-H3 e um checkpoint ControlNet-Union, preservando o movimento e a estrutura da entrada enquanto aplica o seu prompt. Ideal para animação de personagens, transferência de movimento e visualização de coreografias. Este workflow é só para controle de pose.',
  'video_minimax_h3_i2v_continuation': 'Comece com uma imagem e um prompt vazio, depois descreva o movimento, os planos e o áudio que quer que o MiniMax H3 gere. Produz um vídeo com áudio sincronizado e continua totalmente editável antes de rodar.',
  'templates_purz_image_glitch': 'Aplica efeitos de glitch e rasgo personalizáveis a imagens. Controle a intensidade da distorção, a aberração cromática e a aleatoriedade do padrão. Devolve uma imagem estilizada e distorcida.',
  'templates-image_to_real': 'Envie uma ilustração e gere uma versão hiper-realista com o Qwen Image Edit 2509.',
  'templates_purz_pixel_sort_image': 'Aplica um algoritmo de ordenação de pixels para criar glitch art. Controle a direção do efeito, o limiar e a mistura com a imagem original. Devolve uma versão estilizada e "borrada" da entrada.',
  'utility_interpolation_image_upscale': 'Envie uma imagem e escolha o método de interpolação. Amplia com algoritmos tradicionais: mais rápido, com pouca alteração de detalhe.',
  'utility_face_detection_mediapipe': 'Envie uma imagem e detecte até 6 pontos faciais por rosto, com detecção ultrarrápida de vários rostos.',
  'image_qwen_image_layered_control': 'Descreva os elementos que quer na imagem e decomponha-a com precisão em camadas.',
  'templates-6-key-frames': 'Cria um vídeo suave a partir de 6 quadros-chave. Preenche o movimento entre os quadros automaticamente e costura os trechos sem emendas.',
  'utility_seedvr2_video_upscale': 'Envie um vídeo para ampliar e melhorar a resolução com o modelo SeedVR2, gerando uma saída em alta definição.',
  'utility-normal_crafter-video': 'Converte um vídeo em um mapa de normais temporalmente estável.',
  'templates_purz_crossfade': 'Mistura duas sequências de vídeo com um efeito de crossfade. Duas sequências de imagens de entrada, com duração da transição e modo de mistura configuráveis. Devolve uma única sequência de vídeo unida.',
  'templates-qwen_image_edit-crop_and_stitch-fusion': 'Envie uma imagem composta do seu produto, desenhe uma máscara no editor e reilumine o produto dentro da cena.',
}

// Frase genérica para um template que ainda não tem tradução.
const VERBO_POR_TAG: Array<[RegExp, string]> = [
  [/^text to image$/i, 'Gera imagens a partir de texto'],
  [/^image edit$/i, 'Edita imagens por instrução de texto'],
  [/^inpainting$/i, 'Preenche ou substitui regiões de imagens'],
  [/^image upscale$/i, 'Amplia imagens'],
  [/^relight$/i, 'Reilumina imagens'],
  [/^pose map$/i, 'Extrai mapas de pose'],
  [/^layer decompose$/i, 'Decompõe imagens em camadas'],
  [/^text to video$/i, 'Gera vídeos a partir de texto'],
  [/^image to video$/i, 'Anima uma imagem em vídeo'],
  [/^audio to video$/i, 'Gera vídeo sincronizado com um áudio'],
  [/^flf2v$/i, 'Gera vídeo entre um quadro inicial e um final'],
  [/^lip sync$/i, 'Gera vídeo com sincronia labial'],
  [/^video edit$/i, 'Edita vídeos'],
]
const COMPLEMENTO_POR_TAG: Array<[RegExp, string]> = [
  [/^controlnet$/i, 'com controle estrutural (ControlNet)'],
  [/^lora$/i, 'com LoRA'],
  [/^portrait$/i, 'para retratos'],
]

export function descricaoPt(nome: string, tags: string[], familiaNome: string, task: 'image' | 'video'): string {
  const pronta = DESCRICOES_PT[nome]
  if (pronta) return pronta
  const verbo = VERBO_POR_TAG.find(([re]) => tags.some(g => re.test(g)))?.[1]
    ?? (task === 'video' ? 'Gera vídeos' : 'Gera imagens')
  const extras = COMPLEMENTO_POR_TAG.filter(([re]) => tags.some(g => re.test(g))).map(([, s]) => s)
  return `${[verbo, ...extras].join(' ')} usando ${familiaNome}. Workflow oficial do ComfyUI.`
}
// i18n-ignore-end
