// Termos de Uso — fora do dicionário de propósito.
//
// Não é copy de interface: é documento jurídico. Mora separado porque o ciclo de
// revisão é outro (advogado, não tradutor) e porque uma string de 40 linhas no
// meio do dicionário atrapalha a leitura de todas as outras.
//
// ATENÇÃO — a versão em inglês é uma tradução fiel do texto em português, mas
// NÃO foi revisada juridicamente. Dois pontos merecem atenção antes de vender
// fora do Brasil:
//   • O item de reembolso cita a Hotmart e o prazo de 7 dias, que vem do Código
//     de Defesa do Consumidor brasileiro (art. 49). Esse prazo não vale para
//     compradores de outros países.
//   • Não há cláusula de lei aplicável / foro, o que costuma ser esperado em
//     termos voltados ao mercado internacional.

import type { Lang } from './index'

const pt = `TERMOS DE USO — REF MAP
Última atualização: junho de 2026

1. ACEITAÇÃO
Ao acessar e usar o Ref Map, você declara que leu, compreendeu e concorda com estes Termos. Se não concordar, não utilize o aplicativo.

2. O QUE É O REF MAP
O Ref Map é um software desktop para organização de imagens de referência e construção de prompts para ferramentas de IA generativa. O acesso é concedido mediante compra de licença.

3. LICENÇA DE USO
Ao adquirir o Ref Map, você recebe uma licença pessoal, não exclusiva e intransferível para uso do software. É vedado redistribuir, vender, sublicenciar ou compartilhar o acesso com terceiros.

4. DADOS E PRIVACIDADE
• Autenticação: seu e-mail é armazenado em um banco de dados seguro para controle de acesso.
• API Keys: suas chaves de API (Anthropic/OpenAI) são armazenadas localmente no seu dispositivo com criptografia do sistema operacional. Não temos acesso a elas.
• Imagens: suas imagens de referência são armazenadas apenas no seu dispositivo. Não enviamos imagens aos nossos servidores.
• Thumbnails e metadados são processados localmente.

5. CONTEÚDO GERADO POR IA
Os prompts gerados pelo Ref Map pertencem a você. Somos responsáveis pelo funcionamento do software, mas não pela qualidade, adequação ou uso dos prompts gerados. O uso dos prompts em ferramentas de terceiros está sujeito aos termos dessas ferramentas.

6. REEMBOLSOS
A política de reembolso é gerenciada pela Hotmart, plataforma de venda do produto. Pedidos de reembolso devem ser realizados diretamente na Hotmart dentro do prazo legal de 7 dias.

7. LIMITAÇÃO DE RESPONSABILIDADE
O Ref Map é fornecido "como está". Não nos responsabilizamos por danos diretos ou indiretos decorrentes do uso do software, incluindo perda de dados ou uso indevido de conteúdo gerado por IA.

8. USO ADEQUADO
É vedado utilizar o Ref Map para gerar conteúdo ilegal, difamatório, que viole direitos de terceiros ou as políticas das ferramentas de IA integradas.

9. ALTERAÇÕES
Podemos atualizar estes Termos a qualquer momento. Atualizações serão comunicadas no aplicativo. O uso continuado após a notificação implica aceitação.

10. CONTATO
Dúvidas: app@refmap.santinello.com.br`

const en = `TERMS OF USE — REF MAP
Last updated: June 2026

1. ACCEPTANCE
By accessing and using Ref Map, you declare that you have read, understood and agree to these Terms. If you do not agree, do not use the application.

2. WHAT REF MAP IS
Ref Map is desktop software for organizing reference images and building prompts for generative AI tools. Access is granted upon purchase of a license.

3. LICENSE
By purchasing Ref Map, you receive a personal, non-exclusive and non-transferable license to use the software. Redistributing, selling, sublicensing or sharing access with third parties is prohibited.

4. DATA AND PRIVACY
• Authentication: your email is stored in a secure database for access control.
• API Keys: your API keys (Anthropic/OpenAI) are stored locally on your device using operating-system encryption. We have no access to them.
• Images: your reference images are stored only on your device. We do not upload images to our servers.
• Thumbnails and metadata are processed locally.

5. AI-GENERATED CONTENT
The prompts generated by Ref Map belong to you. We are responsible for the operation of the software, but not for the quality, suitability or use of the prompts it generates. Using those prompts in third-party tools is subject to the terms of those tools.

6. REFUNDS
The refund policy is managed by Hotmart, the platform through which the product is sold. Refund requests must be made directly to Hotmart within the 7-day statutory period.

7. LIMITATION OF LIABILITY
Ref Map is provided "as is". We are not liable for direct or indirect damages arising from use of the software, including data loss or misuse of AI-generated content.

8. ACCEPTABLE USE
You may not use Ref Map to generate content that is illegal or defamatory, that infringes the rights of third parties, or that violates the policies of the integrated AI tools.

9. CHANGES
We may update these Terms at any time. Updates will be announced in the application. Continued use after notice constitutes acceptance.

10. CONTACT
Questions: app@refmap.santinello.com.br`

export const TERMS: Record<Lang, string> = { en, pt }
